// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  code: __t.string().primaryKey(),
  picks: __t.i32(),
  passes: __t.i32(),
  big: __t.i32(),
  brt: __t.i32(),
  bsp: __t.i32(),
  cn: __t.i32(),
  crit: __t.i32(),
  cryo: __t.i32(),
  dmg: __t.i32(),
  drn: __t.i32(),
  emd: __t.i32(),
  emp: __t.i32(),
  emr: __t.i32(),
  epd: __t.i32(),
  epw: __t.i32(),
  fr: __t.i32(),
  heal: __t.i32(),
  hm: __t.i32(),
  hms: __t.i32(),
  hp: __t.i32(),
  kb: __t.i32(),
  mag: __t.i32(),
  mc: __t.i32(),
  mov: __t.i32(),
  mp: __t.i32(),
  mrk: __t.i32(),
  nec: __t.i32(),
  oc: __t.i32(),
  pen: __t.i32(),
  shd: __t.i32(),
  sz: __t.i32(),
  vamp: __t.i32(),
});
