// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  userId: __t.string().name("user_id"),
  country: __t.string(),
  guessLat: __t.f64().name("guess_lat"),
  guessLon: __t.f64().name("guess_lon"),
  targetLat: __t.f64().name("target_lat"),
  targetLon: __t.f64().name("target_lon"),
  distanceMi: __t.f64().name("distance_mi"),
  timestamp: __t.u64(),
});
