// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  code: __t.string().primaryKey(),
  hostId: __t.string().name("host_id"),
  seed: __t.string(),
  phase: __t.string(),
  currentQuestion: __t.i32().name("current_question"),
  questionDeadline: __t.u64().name("question_deadline"),
  createdAt: __t.u64().name("created_at"),
});
