// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const LoginCode = __t.object("LoginCode", {
  code: __t.string(),
  accountId: __t.string(),
  createdAt: __t.u64(),
  expiresAt: __t.u64(),
});
export type LoginCode = __Infer<typeof LoginCode>;

export const Party = __t.object("Party", {
  code: __t.string(),
  hostId: __t.string(),
  seed: __t.string(),
  phase: __t.string(),
  currentQuestion: __t.i32(),
  questionDeadline: __t.u64(),
  createdAt: __t.u64(),
});
export type Party = __Infer<typeof Party>;

export const PartyCapital = __t.object("PartyCapital", {
  key: __t.string(),
  code: __t.string(),
  userId: __t.string(),
  question: __t.i32(),
  distanceMi: __t.f64(),
  timestamp: __t.u64(),
});
export type PartyCapital = __Infer<typeof PartyCapital>;

export const PartyConfig = __t.object("PartyConfig", {
  code: __t.string(),
  modeA: __t.string(),
  modeB: __t.string(),
  mode: __t.string(),
});
export type PartyConfig = __Infer<typeof PartyConfig>;

export const PartyEvent = __t.object("PartyEvent", {
  key: __t.string(),
  code: __t.string(),
  userId: __t.string(),
  name: __t.string(),
  kind: __t.string(),
  detail: __t.string(),
  timestamp: __t.u64(),
});
export type PartyEvent = __Infer<typeof PartyEvent>;

export const PartyGuess = __t.object("PartyGuess", {
  key: __t.string(),
  code: __t.string(),
  question: __t.i32(),
  userId: __t.string(),
  name: __t.string(),
  correct: __t.bool(),
  timestamp: __t.u64(),
});
export type PartyGuess = __Infer<typeof PartyGuess>;

export const PartyPlayer = __t.object("PartyPlayer", {
  key: __t.string(),
  code: __t.string(),
  userId: __t.string(),
  name: __t.string(),
  ready: __t.bool(),
  score: __t.i32(),
  joinedAt: __t.u64(),
});
export type PartyPlayer = __Infer<typeof PartyPlayer>;

export const PartyVote = __t.object("PartyVote", {
  key: __t.string(),
  code: __t.string(),
  userId: __t.string(),
  mode: __t.string(),
});
export type PartyVote = __Infer<typeof PartyVote>;

export const Progress = __t.object("Progress", {
  accountId: __t.string(),
  data: __t.string(),
  updatedAt: __t.u64(),
});
export type Progress = __Infer<typeof Progress>;

