// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CountryStat = __t.object("CountryStat", {
  country: __t.string(),
  correct: __t.i32(),
  total: __t.i32(),
});
export type CountryStat = __Infer<typeof CountryStat>;

export const Guess = __t.object("Guess", {
  id: __t.u64(),
  userId: __t.string(),
  target: __t.string(),
  guess: __t.string(),
  correct: __t.bool(),
  lat: __t.f64(),
  lon: __t.f64(),
  timestamp: __t.u64(),
});
export type Guess = __Infer<typeof Guess>;

export const UserCountryStat = __t.object("UserCountryStat", {
  key: __t.string(),
  userId: __t.string(),
  country: __t.string(),
  correct: __t.i32(),
  total: __t.i32(),
});
export type UserCountryStat = __Infer<typeof UserCountryStat>;

