// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdvanceQuestionReducer from "../advance_question_reducer";
import CreatePartyReducer from "../create_party_reducer";
import GenerateLoginCodeReducer from "../generate_login_code_reducer";
import JoinPartyReducer from "../join_party_reducer";
import LeavePartyReducer from "../leave_party_reducer";
import RedeemLoginCodeReducer from "../redeem_login_code_reducer";
import RestartPartyReducer from "../restart_party_reducer";
import SaveProgressReducer from "../save_progress_reducer";
import SetReadyReducer from "../set_ready_reducer";
import SetVoteReducer from "../set_vote_reducer";
import SubmitPartyGuessReducer from "../submit_party_guess_reducer";
import UsePartyLifelineReducer from "../use_party_lifeline_reducer";

export type AdvanceQuestionParams = __Infer<typeof AdvanceQuestionReducer>;
export type CreatePartyParams = __Infer<typeof CreatePartyReducer>;
export type GenerateLoginCodeParams = __Infer<typeof GenerateLoginCodeReducer>;
export type JoinPartyParams = __Infer<typeof JoinPartyReducer>;
export type LeavePartyParams = __Infer<typeof LeavePartyReducer>;
export type RedeemLoginCodeParams = __Infer<typeof RedeemLoginCodeReducer>;
export type RestartPartyParams = __Infer<typeof RestartPartyReducer>;
export type SaveProgressParams = __Infer<typeof SaveProgressReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type SetVoteParams = __Infer<typeof SetVoteReducer>;
export type SubmitPartyGuessParams = __Infer<typeof SubmitPartyGuessReducer>;
export type UsePartyLifelineParams = __Infer<typeof UsePartyLifelineReducer>;

